# 在master分支发生push事件时触发。
name: CodeCoverageTest

on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  CodeCov: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest
    steps:
      - name: Check out master code
        uses: actions/checkout@master
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean compile test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./rpamis-security-test/target/site/jacoco-aggregate/jacoco.xml
          flags: unittests
          name: codecov-jacoco-rpamis-security
          verbose: true
